apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spotify-recommendations-eksctl
  region: "${AWS_REGION}"
  version: "1.21"

availabilityZones: ["${AZS[0]}", "${AZS[1]}", "${AZS[2]}"]

managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 3
    instanceType: t3.small
# To disable all of the control plane logs, comment below:
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

secretsEncryption:
  keyARN: ${MASTER_ARN}
