apiVersion: v1
kind: Service
metadata:
  name: spotify-recommendations
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: spotify-recommendations
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-recommendations
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: spotify-recommendations
  template:
    metadata:
      labels:
        app: spotify-recommendations
    spec:
      containers:
        - name: spotify-recommendations
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          env:
            - name: DATA_DIR
              value: "s3://spotify_recommendations"
            - name: MLFLOW_TRACKING_URI
              value: "http://deplo-mlflo-16g0oyp6k65hv-5cd5faf094caf332.elb.us-east-1.amazonaws.com/"
            - name: EXPERIMENT_NAME
              value: "spotify_recommendations"
            - name: MODEL_ID
              value: "c59730008fac4f249afd527798f57c4e"
          # envFrom:
          #   - secretRef:
          #       name: mysecret
          ports:
            - containerPort: 5000
